/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOG_RPC_H_RPCGEN
#define _LOG_RPC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct log_request {
	char *user;
	char *operation;
	char *filename;
};
typedef struct log_request log_request;

#define LOG_RPC_PROG 0x20000099
#define LOG_RPC_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define LOG_OPERATION 1
extern  int * log_operation_1(log_request *, CLIENT *);
extern  int * log_operation_1_svc(log_request *, struct svc_req *);
extern int log_rpc_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LOG_OPERATION 1
extern  int * log_operation_1();
extern  int * log_operation_1_svc();
extern int log_rpc_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_log_request (XDR *, log_request*);

#else /* K&R C */
extern bool_t xdr_log_request ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOG_RPC_H_RPCGEN */
