/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "log_rpc.h"

bool_t
xdr_log_request (XDR *xdrs, log_request *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->user, 255))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operation, 32))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->filename, 255))
		 return FALSE;
	return TRUE;
}
